# -*- coding: utf-8 -*-
"""distribuição GEV

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1886tAPwMWWTbV10ROvxSzkC7jmPxZkiG
"""

import numpy as np
from scipy.stats import genextreme
import matplotlib.pyplot as plt

# gerar dados aleatórios com distribuição GEV
dados = genextreme.rvs(c=0.5, loc=0, scale=1, size=1000)

# ajustar a distribuição GEV aos dados
params = genextreme.fit(dados)

# imprimir os parâmetros da distribuição ajustada
print(params)

# plotar o histograma dos dados e a PDF da distribuição ajustada
x = np.linspace(genextreme.ppf(0.001, *params), genextreme.ppf(0.999, *params), 100)
pdf = genextreme.pdf(x, *params)
plt.hist(dados, bins=30, density=True, alpha=0.5)
plt.plot(x, pdf, 'r-', lw=2)
plt.xlabel('Valor')
plt.ylabel('Frequência')
plt.show()